### PR TITLE
feat: YOLO import includes images without label files

### PR DESCRIPTION
**Pull request by Mekcyed**
Hey,

Firstly: thanks for this toolbox which saved me a lot of time.

I noticed with the yolo import function, that it does not include images which do not have a corresponding label file. But when creating predictions/ annotations with yolo it can happen that yolo does not detect anything. In this case no label txt file is created.

I propose a change of the converting loop in `yolo.py`. 

Instead of looping through the folder with the label files it should loop through the image folder. The output for the label-studio `json` file would now include images without predictions/ annotations:

```
[      
        {
        "data": {
            "image": "/data/local-files/?d=/folder/image.jpg"
        },
        "predictions": [
            {
                "result": [
                    {
                        "id": "498b1bfa94",
                        "type": "rectanglelabels",
                        "value": {
                            "x": 3.4374700000000007,
                            "y": 0.18516999999999978,
                            "width": 12.9688,
                            "height": 17.963,
                            "rotation": 0,
                            "rectanglelabels": [
                                "person"
                            ]
                        },
                        "to_name": "image",
                        "from_name": "label",
                        "image_rotation": 0,
                        "original_width": 1920,
                        "original_height": 1080
                    },
                    {
                        "id": "d297476aa9",
                        "type": "rectanglelabels",
                        "value": {
                            "x": 0.05205999999999961,
                            "y": 4.537050000000001,
                            "width": 14.218800000000002,
                            "height": 33.4259,
                            "rotation": 0,
                            "rectanglelabels": [
                                "person"
                            ]
                        },
                        "to_name": "image",
                        "from_name": "label",
                        "image_rotation": 0,
                        "original_width": 1920,
                        "original_height": 1080
                    }
                ],
                "ground_truth": false
            }
        ]
    },
    {
        "data": {
            "image": "/data/local-files/?d=/folder/image.jpg"
        }
    }
]
```

### CODE REVIEW

**Comment by makseq** [comment]
@Mekcyed do you mind to add test for yolo import?

**Comment by Mekcyed** [comment]
@makseq  Could you give some hints on what you would like to see in a yolo test? And are there functions to validate whether a json is valid to be imported to label-studio?

**Comment by makseq** [comment]
> @makseq Could you give some hints on what you would like to see in a yolo test? And are there functions to validate whether a json is valid to be imported to label-studio?

It would be great to see how ls converter takes a folder with yolo images and labeling files and generates the output LS json. So, we can check this generated json with ground truth json that we've prepared beforehand for this test.

**Comment by makseq** [comment]
please, resolve conflict with master

**Comment by Mekcyed** [comment]
Failed the merge first und reopend the pr...

**Review by makseq — APPROVED** [review]

**Pull request merged**
